#!/bin/bash

# Скрипт для подготовки QloApps к развертыванию на хостинге
# Использование: ./deploy_prepare.sh

echo "========================================="
echo "  Подготовка QloApps к развертыванию"
echo "========================================="
echo ""

# Цвета для вывода
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Проверка, что скрипт запускается из корня проекта
if [ ! -f "config/config.inc.php" ]; then
    echo -e "${RED}Ошибка: Скрипт должен запускаться из корневой директории QloApps${NC}"
    exit 1
fi

# Создание директории для деплоя
DEPLOY_DIR="qloapps_deploy_$(date +%Y%m%d_%H%M%S)"
echo -e "${YELLOW}Создание директории для деплоя: ${DEPLOY_DIR}${NC}"
mkdir -p "../${DEPLOY_DIR}"

# Копирование файлов (исключая ненужные)
echo -e "${YELLOW}Копирование файлов...${NC}"
rsync -av --progress \
    --exclude='.git' \
    --exclude='.gitignore' \
    --exclude='.DS_Store' \
    --exclude='node_modules' \
    --exclude='*.log' \
    --exclude='cache/smarty/cache/*' \
    --exclude='cache/smarty/compile/*' \
    --exclude='config/settings.inc.php' \
    --exclude='config/defines.inc.php' \
    --exclude='img/p/*' \
    --exclude='img/c/*' \
    --exclude='download/*' \
    --exclude='upload/*' \
    --exclude='.htaccess' \
    --exclude='robots.txt' \
    ./ "../${DEPLOY_DIR}/"

# Создание необходимых пустых директорий
echo -e "${YELLOW}Создание необходимых директорий...${NC}"
mkdir -p "../${DEPLOY_DIR}/cache/smarty/cache"
mkdir -p "../${DEPLOY_DIR}/cache/smarty/compile"
mkdir -p "../${DEPLOY_DIR}/log"
mkdir -p "../${DEPLOY_DIR}/download"
mkdir -p "../${DEPLOY_DIR}/upload"
mkdir -p "../${DEPLOY_DIR}/img/p"
mkdir -p "../${DEPLOY_DIR}/img/c"

# Создание .htaccess для production
echo -e "${YELLOW}Создание .htaccess для production...${NC}"
cat > "../${DEPLOY_DIR}/.htaccess" << 'EOF'
# ~~start~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
# .htaccess automaticaly generated by PrestaShop e-commerce open-source solution
# http://www.prestashop.com - http://www.prestashop.com/forums

<IfModule mod_rewrite.c>
<IfModule mod_env.c>
SetEnv HTTP_MOD_REWRITE On
</IfModule>

RewriteEngine on

# Force HTTPS
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

# Disable MultiViews
Options -MultiViews

# URL rewriting
RewriteRule . - [E=REWRITEBASE:/]
RewriteRule ^api/?(.*)$ %{ENV:REWRITEBASE}webservice/dispatcher.php?url=$1 [QSA,L]

# Redirect к index.php
RewriteCond %{REQUEST_URI} !^/[0-9]+\..+\.cpaneldcv$
RewriteCond %{REQUEST_URI} !^/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
RewriteCond %{REQUEST_URI} !^/\.well-known/pki-validation/[A-F0-9]{32}\.txt(?:\ Comodo\ DCV)?$
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ %{ENV:REWRITEBASE}index.php [QSA,L]
</IfModule>

# Защита от SQL инъекций
<IfModule mod_rewrite.c>
RewriteCond %{QUERY_STRING} [a-zA-Z0-9_]=http:// [OR]
RewriteCond %{QUERY_STRING} [a-zA-Z0-9_]=(\.\.//?)+ [OR]
RewriteCond %{QUERY_STRING} [a-zA-Z0-9_]=/([a-z0-9_.]//?)+ [NC]
RewriteRule .* - [F]
</IfModule>

# Защита файлов конфигурации
<FilesMatch "\.(htaccess|htpasswd|ini|log|sh|inc|bak|swp|sql)$">
    Order Allow,Deny
    Deny from all
</FilesMatch>

# GZIP compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript application/x-javascript application/json
</IfModule>

# Browser caching
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/webp "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType text/javascript "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
    ExpiresByType application/x-javascript "access plus 1 month"
    ExpiresByType application/pdf "access plus 1 month"
    ExpiresByType application/x-shockwave-flash "access plus 1 month"
    ExpiresByType image/x-icon "access plus 1 year"
</IfModule>

# Security headers
<IfModule mod_headers.c>
    Header always set X-Content-Type-Options "nosniff"
    Header always set X-XSS-Protection "1; mode=block"
    Header always set X-Frame-Options "SAMEORIGIN"
</IfModule>

# PHP settings
<IfModule mod_php7.c>
    php_value max_execution_time 500
    php_value max_input_time 500
    php_value memory_limit 128M
    php_value upload_max_filesize 100M
    php_value post_max_size 100M
    php_flag display_errors off
    php_flag log_errors on
</IfModule>

# ~~end~~ Do not remove this comment, Prestashop will keep automatically the code outside this comment when .htaccess will be generated again
EOF

# Создание robots.txt
echo -e "${YELLOW}Создание robots.txt...${NC}"
cat > "../${DEPLOY_DIR}/robots.txt" << 'EOF'
User-agent: *
Disallow: /admin/
Disallow: /admin-dev/
Disallow: /upload/
Disallow: /download/
Disallow: /modules/
Disallow: /cache/
Disallow: /config/
Disallow: /classes/
Disallow: /translations/
Disallow: /login
Disallow: /password
Disallow: /search
Disallow: /cart
Disallow: /my-account
Disallow: /order
Disallow: /*?*
Allow: /modules/*.css
Allow: /modules/*.js
Allow: /modules/*.jpg
Allow: /modules/*.png

Sitemap: https://your-domain.com/sitemap.xml
EOF

# Создание архива
echo -e "${YELLOW}Создание архива для загрузки...${NC}"
cd "../${DEPLOY_DIR}" || exit
tar -czf "../${DEPLOY_DIR}.tar.gz" .
cd - > /dev/null

# Создание архива ZIP (альтернатива)
cd "../${DEPLOY_DIR}" || exit
zip -r "../${DEPLOY_DIR}.zip" . -q
cd - > /dev/null

# Информация о размере
TARSIZE=$(du -h "../${DEPLOY_DIR}.tar.gz" | cut -f1)
ZIPSIZE=$(du -h "../${DEPLOY_DIR}.zip" | cut -f1)

echo ""
echo -e "${GREEN}========================================="
echo -e "  Подготовка завершена успешно!"
echo -e "=========================================${NC}"
echo ""
echo -e "Созданы следующие файлы:"
echo -e "  📁 Директория: ${YELLOW}../${DEPLOY_DIR}/${NC}"
echo -e "  📦 TAR архив: ${YELLOW}../${DEPLOY_DIR}.tar.gz${NC} (${TARSIZE})"
echo -e "  📦 ZIP архив: ${YELLOW}../${DEPLOY_DIR}.zip${NC} (${ZIPSIZE})"
echo ""
echo -e "${YELLOW}Следующие шаги:${NC}"
echo "  1. Загрузите архив на хостинг через FTP/SFTP или SSH"
echo "  2. Распакуйте архив в корневую директорию веб-сервера"
echo "  3. Создайте базу данных MySQL"
echo "  4. Откройте http://your-domain.com/install/ для начала установки"
echo ""
echo -e "${YELLOW}Команды для загрузки (примеры):${NC}"
echo ""
echo "  # Через SCP:"
echo "  scp ../${DEPLOY_DIR}.tar.gz user@your-server.com:/var/www/html/"
echo ""
echo "  # На сервере распаковать:"
echo "  tar -xzf ${DEPLOY_DIR}.tar.gz"
echo ""
echo -e "${GREEN}Подробная инструкция в файле: DEPLOYMENT_GUIDE_RU.md${NC}"
echo ""

