services:
  db:
    image: mysql:8.0
    container_name: qloapps_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: qloapps
      MYSQL_USER: qloapps
      MYSQL_PASSWORD: qloappspass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    image: php:8.1-apache
    container_name: qloapps_web
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/conf.d/local.ini:ro
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: qloapps_phpmyadmin
    depends_on:
      - db
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"

volumes:
  db_data:
