[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.curl", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.soap", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.simplexml", "php82Extensions.dom"]

[phases.install]
cmds = ["echo 'Installing dependencies...'"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t ."

